[package]
name = "storage_system"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
eframe = {version = "0.28.1", features = ["default"]}
rand = "0.8.5"
lb-rs = { git = "https://github.com/lockbook/lockbook" }